server:
  port: 18082
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jabc:mysql://192.168.164.38:3306/guli_sms
  redis:
    port: 6379
    host: 192.168.164.38
feign:
  sentinel:
    enabled: true
    mybatis-plus:
      mapper-locations: classpath:mapper/pms/**/*.xml #读取映射文件
      configuration:
        global-config:
          db-config:
            id-type: auto #默认使用数据库自增
        type-aliases-package: com.atguigu.gmall.pms.entity
