server:
  port: 18081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.164.38:3306/guli_pms
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.164.38
    port: 6379
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/pms/**/*.xml
  configuration:
    global-config:
      db-config:
        id-type: auto
    type-aliases-package: com.atguigu.gmall.pms.entity

